[package]
name = "fx_sim_agg"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
futures = "0.3"
tokio = { version = "1", default-features = false, features = [
    "fs",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-stream = "0.1"